# Generated by Django 4.1.1 on 2022-09-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress_Master',
            fields=[
                ('progress_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField()),
                ('progress_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todoapp.progress_master')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todoapp.users')),
            ],
        ),
    ]
