# Generated by Django 4.1.1 on 2022-09-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_progress_master_users_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
