# Generated by Django 4.1.1 on 2022-09-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_tasks_task_rename_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestData',
        ),
        migrations.AlterField(
            model_name='progress_master',
            name='progress_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
